"""Agent Value Objects - Types for agent communication"""
from dataclasses import dataclass
from datetime import datetime
from typing import Dict, Any, List, Optional
from enum import Enum


class AgentMessageType(str, Enum):
    """Agent message type enumeration"""
    INIT = "init"
    TEXT = "text"
    TOOL_USE = "tool_use"
    TOOL_RESULT = "tool_result"
    ERROR = "error"
    COMPLETE = "complete"


@dataclass(frozen=True)
class ToolCallVO:
    """Tool call information Value Object"""
    id: str
    name: str
    input: Dict[str, Any]


@dataclass(frozen=True)
class AgentStreamEvent:
    """
    Agent streaming event Value Object

    Each event represents an individual response unit generated by the agent.
    """
    type: AgentMessageType
    content: Optional[str] = None          # Text content for TEXT type
    tool_call: Optional[ToolCallVO] = None  # Tool call info for TOOL_USE type
    claude_session_id: Optional[str] = None   # Session ID for INIT type
    error: Optional[str] = None            # Error message for ERROR type


@dataclass(frozen=True)
class SessionStatusVO:
    """
    Session status information Value Object

    Replaces Dict[str, Any] return from get_session_status().
    """
    session_id: str
    status: str
    message_count: int
    created_at: datetime
    updated_at: Optional[datetime]
    archived_at: Optional[datetime]


@dataclass(frozen=True)
class MessageEnqueueResultVO:
    """
    Message enqueue result Value Object

    Replaces Dict[str, Any] return from enqueue_message().
    """
    session_id: str
    status: str
    user_message_id: str


@dataclass(frozen=True)
class GrowthMemorySummaryVO:
    """
    Growth Memory summarization result Value Object

    Contains 6 structured summary units extracted from session conversation.
    Used as intermediate result from Claude summarization before entity creation.
    """
    problem_snapshot: Optional[str]
    bottleneck_evidence: Optional[str]
    hypotheses: Optional[List[str]]
    experiment_cards: Optional[List[Dict[str, Any]]]
    outcome: Optional[str]
    learnings_next_actions: Optional[str]


@dataclass(frozen=True)
class SubAgentExecutionResult:
    """
    Sub-agent execution result Value Object

    Contains the final response and all internal events for trace storage.
    Used to capture sub-agent behavior for debugging and analysis.
    """
    final_response: str
    events: List[Dict[str, Any]]
    started_at: datetime
    completed_at: datetime
    duration_ms: int
    error: Optional[str] = None
