"""Agent Value Objects - Types for agent communication"""
from dataclasses import dataclass
from typing import Dict, Any, Optional, Tuple
from enum import Enum


class AgentMessageType(str, Enum):
    """Agent message type enumeration"""
    INIT = "init"
    TEXT = "text"
    TOOL_USE = "tool_use"
    TOOL_RESULT = "tool_result"
    ERROR = "error"
    COMPLETE = "complete"


@dataclass(frozen=True)
class ToolCallVO:
    """Tool call information Value Object"""
    id: str
    name: str
    input: Dict[str, Any]


@dataclass(frozen=True)
class AgentStreamEvent:
    """
    Agent streaming event Value Object

    Each event represents an individual response unit generated by the agent.
    """
    type: AgentMessageType
    content: Optional[str] = None          # Text content for TEXT type
    tool_call: Optional[ToolCallVO] = None  # Tool call info for TOOL_USE type
    sdk_session_id: Optional[str] = None   # Session ID for INIT type
    error: Optional[str] = None            # Error message for ERROR type


@dataclass(frozen=True)
class AgentResponse:
    """
    Agent final response Value Object

    Replaces Dict[str, Any] return type with type-safe immutable object.
    """
    text_response: str
    tool_calls: Tuple[ToolCallVO, ...]  # Tuple for immutability
    sdk_session_id: Optional[str]
    message_count: int = 0
